### ISSUE TITLE
Naming Convention

### ISSUE THREAD

**Issue by alima-kailamarie** [PUP-BSIT/ex7-tuf_developers#1]
Class names should be written in kebab case. Refer to the coding guidelines below:
- - -
https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit?fbclid=IwAR1lw-fYFJoyU3Zd8xuasXE5Pi9M6HBHNvyXQhX_UigWsIFh_HM5tA-jJBw_aem_AZw6dkk88Ijvd-vTmoWhtyHTRRxWo93wb9ZLBom35XLUH8Yj_gBMV4naXQt39pb5oz2vkfvSXebSNNTl0ZO6fXbx#slide=id.g24da8de92d7_0_5

https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/anonuevo_jheferson/anonuevo_jheferson.html#L12
https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/anonuevo_jheferson/anonuevo_jheferson.html#L23

**Comment by Cruz-Simounne** [comment]
@donatos-andrea 

The file name of 1.css should be specific to make it easier to understand the purpose and content of the CSS file.

- - -


The variable names should be descriptive. Refer to this slide:  https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit?fbclid=IwAR1lw-fYFJoyU3Zd8xuasXE5Pi9M6HBHNvyXQhX_UigWsIFh_HM5tA-jJBw_aem_AZw6dkk88Ijvd-vTmoWhtyHTRRxWo93wb9ZLBom35XLUH8Yj_gBMV4naXQt39pb5oz2vkfvSXebSNNTl0ZO6fXbx#slide=id.g25d18931cb7_3_0

https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/donatos_andrea/donatos_andrea.html#L3

https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/donatos_andrea/donatos_andrea.html#L7

https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/donatos_andrea/donatos_andrea.html#L11

https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/donatos_andrea/donatos_andrea.html#L21

https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/donatos_andrea/donatos_andrea.html#L22

https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/donatos_andrea/donatos_andrea.html#L33

https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/donatos_andrea/donatos_andrea.html#L41

https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/donatos_andrea/practice%202.html#L4

https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/donatos_andrea/practice%203.html#L4

https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/donatos_andrea/practice%204.html#L4

https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/donatos_andrea/practice%205.html#L4

https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/donatos_andrea/practice.html#L4

- - -

**Comment by mingoedjudah** [comment]
@nogadas-vonryan 

All files should be named snake case. Refer to slide 15 second bullet of the coding guidelines.

https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/nogadas_vonryan/nogadas_vonryan.html#L24

https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/nogadas_vonryan/nogadas_vonryan.html#L27

https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/nogadas_vonryan/nogadas_vonryan.html#L30

https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/nogadas_vonryan/nogadas_vonryan.html#L33

https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/nogadas_vonryan/nogadas_vonryan.html#L36

https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/nogadas_vonryan/nogadas_vonryan.html#L39

---
Coding Guidelines:
https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit?fbclid=IwAR38oipQEtK5lSu37SXTl3zwpEu9ap1GZPut5-F-LVDu6GtoJ1KpPIxhMCs#slide=id.g25d18931cb7_3_0

**Comment by alima-kailamarie** [comment]
Class names should be written in kebab case. Refer to the coding guidelines below:
- - -
https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit?fbclid=IwAR1lw-fYFJoyU3Zd8xuasXE5Pi9M6HBHNvyXQhX_UigWsIFh_HM5tA-jJBw_aem_AZw6dkk88Ijvd-vTmoWhtyHTRRxWo93wb9ZLBom35XLUH8Yj_gBMV4naXQt39pb5oz2vkfvSXebSNNTl0ZO6fXbx#slide=id.g24da8de92d7_0_5

https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/roche_mauijane/roche_mauijane.html#L14

**Comment by Anonuevo-Jheferson** [comment]
> Class names should be written in kebab case. Refer to the coding guidelines below:
> 
> https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit?fbclid=IwAR1lw-fYFJoyU3Zd8xuasXE5Pi9M6HBHNvyXQhX_UigWsIFh_HM5tA-jJBw_aem_AZw6dkk88Ijvd-vTmoWhtyHTRRxWo93wb9ZLBom35XLUH8Yj_gBMV4naXQt39pb5oz2vkfvSXebSNNTl0ZO6fXbx#slide=id.g24da8de92d7_0_5
> 
> https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/anonuevo_jheferson/anonuevo_jheferson.html#L12
> 
> 
> https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/anonuevo_jheferson/anonuevo_jheferson.html#L23

Resolved the issue, fix on 6bb4a68b44852d166a53177f7b25fa33840cc8f9. Thank you

**Comment by Donatos-Andrea** [comment]
> @donatos-andrea
> 
> The file name of 1.css should be specific to make it easier to understand the purpose and content of the CSS file.
> 
> The variable names should be descriptive. Refer to this slide: https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit?fbclid=IwAR1lw-fYFJoyU3Zd8xuasXE5Pi9M6HBHNvyXQhX_UigWsIFh_HM5tA-jJBw_aem_AZw6dkk88Ijvd-vTmoWhtyHTRRxWo93wb9ZLBom35XLUH8Yj_gBMV4naXQt39pb5oz2vkfvSXebSNNTl0ZO6fXbx#slide=id.g25d18931cb7_3_0
> 
> https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/donatos_andrea/donatos_andrea.html#L3
> 
> https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/donatos_andrea/donatos_andrea.html#L7
> 
> https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/donatos_andrea/donatos_andrea.html#L11
> 
> https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/donatos_andrea/donatos_andrea.html#L21
> 
> https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/donatos_andrea/donatos_andrea.html#L22
> 
> https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/donatos_andrea/donatos_andrea.html#L33
> 
> https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/donatos_andrea/donatos_andrea.html#L41
> 
> https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/donatos_andrea/practice%202.html#L4
> 
> https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/donatos_andrea/practice%203.html#L4
> 
> https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/donatos_andrea/practice%204.html#L4
> 
> https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/donatos_andrea/practice%205.html#L4
> 
> https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/donatos_andrea/practice.html#L4

Resolved issue. fix on 5f3bdd4add98f0c8babd5d7e2150bc4f31c051f6. Thank you.

**Comment by Roche-MauiJane** [comment]
> Class names should be written in kebab case. Refer to the coding guidelines below:
> 
> https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit?fbclid=IwAR1lw-fYFJoyU3Zd8xuasXE5Pi9M6HBHNvyXQhX_UigWsIFh_HM5tA-jJBw_aem_AZw6dkk88Ijvd-vTmoWhtyHTRRxWo93wb9ZLBom35XLUH8Yj_gBMV4naXQt39pb5oz2vkfvSXebSNNTl0ZO6fXbx#slide=id.g24da8de92d7_0_5
> 
> https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/roche_mauijane/roche_mauijane.html#L14

Resolved the issue, Fix on 364620257dc9045abca17e784cabcc69e0eac334. Thank you.
