### ISSUE TITLE
Proper Indentation

### ISSUE THREAD

**Issue by Cruz-Simounne** [PUP-BSIT/ex7-tuf_developers#2]
@donatos-andrea 

Must have proper indentation. Line 8 and Line 11 should have the same indentation. Refer to the slide: https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g24acb740da7_0_50

https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/donatos_andrea/donatos_andrea.html#L8C1-L19C20

- - -

**Comment by donatos-andrea** [comment]
fix on 5f3bdd4add98f0c8babd5d7e2150bc4f31c051f6

**Comment by Donatos-Andrea** [comment]
> @donatos-andrea
> 
> Must have proper indentation. Line 8 and Line 11 should have the same indentation. Refer to the slide: https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g24acb740da7_0_50
> 
> https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/donatos_andrea/donatos_andrea.html#L8C1-L19C20

Issue resolved. fix on 5f3bdd4add98f0c8babd5d7e2150bc4f31c051f6. thank you.
