### ISSUE TITLE
Exceed 80 columns

### ISSUE THREAD

**Issue by mingoedjudah** [PUP-BSIT/ex7-tuf_developers#4]
@nogadas-vonryan 

There should be a max of 80 col per line. Refer to slide 6 of the coding guidelines.
https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/nogadas_vonryan/work1.html#L7

https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/nogadas_vonryan/work2.html#L7

https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/nogadas_vonryan/work3.html#L7

https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/nogadas_vonryan/work4.html#L7

https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/nogadas_vonryan/work5.html#L7

https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/nogadas_vonryan/work6.html#L7

---
Coding Guidelines:
https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit?fbclid=IwAR38oipQEtK5lSu37SXTl3zwpEu9ap1GZPut5-F-LVDu6GtoJ1KpPIxhMCs#slide=id.g24da8de92d7_0_0

**Comment by Cruz-Simounne** [comment]
@donatos-andrea 

line exceeded 80 columns. See https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g24da8de92d7_0_0 

https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/donatos_andrea/1.css#L2


https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/donatos_andrea/andrea.css#L6

- - -

**Comment by Villamarzo-Kazel** [comment]
@cahigan-marklouie 
There should be a max of 80 col per line. Refer to slide 6 of the coding guidelines
Coding Guidelines: https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g24da8de92d7_0_0

https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/cahigan_marklouie/cahigan_marklouie.html#L51
https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/cahigan_marklouie/work1.html#L19

**Comment by alima-kailamarie** [comment]
line exceeded 80 columns. Refer to slide 6 of the coding guidelines below:
- - - 
https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g24da8de92d7_0_0

https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/index.html#L16

https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/index.html#L19

https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/index.html#L22

https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/index.html#L25

https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/index.html#L28

**Comment by alima-kailamarie** [comment]
line exceeded 80 columns. Refer to slide 6 of the coding guidelines below:
- - -
https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g24da8de92d7_0_0

https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/roche_mauijane/mauijane.css#L2

https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/roche_mauijane/mauijane.css#L12

https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/roche_mauijane/mauijane.css#L33

https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/roche_mauijane/mauijane.css#L46

@roche-mauijane

**Comment by nogadas-vonryan** [comment]
> @nogadas-vonryan
> 
> There should be a max of 80 col per line. Refer to slide 6 of the coding guidelines.
> 
> https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/nogadas_vonryan/work1.html#L7
> 
> https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/nogadas_vonryan/work2.html#L7
> 
> https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/nogadas_vonryan/work3.html#L7
> 
> https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/nogadas_vonryan/work4.html#L7
> 
> https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/nogadas_vonryan/work5.html#L7
> 
> https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/nogadas_vonryan/work6.html#L7
> 
> Coding Guidelines: https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit?fbclid=IwAR38oipQEtK5lSu37SXTl3zwpEu9ap1GZPut5-F-LVDu6GtoJ1KpPIxhMCs#slide=id.g24da8de92d7_0_0

Issue resolved. Fix on 26b7e30. Thank you.

**Comment by nogadas-vonryan** [comment]
> line exceeded 80 columns. Refer to slide 6 of the coding guidelines below:
> 
> https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g24da8de92d7_0_0
> 
> https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/index.html#L16
> 
> https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/index.html#L19
> 
> https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/index.html#L22
> 
> https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/index.html#L25
> 
> https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/index.html#L28

Issue resolved. Fix on 59e3dbf. Thank you.

**Comment by Cahigan-MarkLouie** [comment]
> @cahigan-marklouie There should be a max of 80 col per line. Refer to slide 6 of the coding guidelines Coding Guidelines: https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g24da8de92d7_0_0
> 
> https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/cahigan_marklouie/cahigan_marklouie.html#L51
> 
> 
> https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/cahigan_marklouie/work1.html#L19

Fix on 38c9b8748f0d484e6cd72fbdc3c43f5c302ea3ea . Thank you.

**Comment by Anonuevo-Jheferson** [comment]
> line exceeded 80 columns. Refer to slide 6 of the coding guidelines below:
> 
> https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g24da8de92d7_0_0
> 
> https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/index.html#L16
> 
> https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/index.html#L19
> 
> https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/index.html#L22
> 
> https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/index.html#L25
> 
> https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/index.html#L28

Resolved the issue, fix on 6bb4a68b44852d166a53177f7b25fa33840cc8f9. Thank you

**Comment by Donatos-Andrea** [comment]
> @donatos-andrea
> 
> line exceeded 80 columns. See https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g24da8de92d7_0_0
> 
> https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/donatos_andrea/1.css#L2
> 
> https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/donatos_andrea/andrea.css#L6

Issue resolved. fix on 5f3bdd4add98f0c8babd5d7e2150bc4f31c051f6. Thank you.

**Comment by Roche-MauiJane** [comment]
> line exceeded 80 columns. Refer to slide 6 of the coding guidelines below:
> 
> https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g24da8de92d7_0_0
> 
> https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/roche_mauijane/mauijane.css#L2
> 
> https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/roche_mauijane/mauijane.css#L12
> 
> https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/roche_mauijane/mauijane.css#L33
> 
> https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/roche_mauijane/mauijane.css#L46
> 
> @roche-mauijane

Resolved the issue, Fix on 364620257dc9045abca17e784cabcc69e0eac334. Thank you.
