### ISSUE TITLE
File Naming

### ISSUE THREAD

**Issue by Villamarzo-Kazel** [PUP-BSIT/ex7-tuf_developers#5]
@cahigan-marklouie 
All files should be named snake case. Refer to slide 15 second bullet of the coding guidelines.
https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit?fbclid=IwAR1lw-fYFJoyU3Zd8xuasXE5Pi9M6HBHNvyXQhX_UigWsIFh_HM5tA-jJBw_aem_AZw6dkk88Ijvd-vTmoWhtyHTRRxWo93wb9ZLBom35XLUH8Yj_gBMV4naXQt39pb5oz2vkfvSXebSNNTl0ZO6fXbx#slide=id.g25d18931cb7_3_0

https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/cahigan_marklouie/cahigan_marklouie.html#L31
https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/cahigan_marklouie/cahigan_marklouie.html#L34
https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/cahigan_marklouie/cahigan_marklouie.html#L37
https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/cahigan_marklouie/cahigan_marklouie.html#L40
https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/cahigan_marklouie/cahigan_marklouie.html#L43
https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/cahigan_marklouie/cahigan_marklouie.html#L5

**Comment by KazelVillamarzo** [comment]
Coding Guidelines Link:
https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit?fbclid=IwAR1NedqsVbFU6sttD7PHWY_LwIgwk77tNKbi3OaYLP3-PnhytI-J4or5nZY#slide=id.g25d18931cb7_3_0

**Comment by KazelVillamarzo** [comment]
Coding Guidelines Link:
https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit?fbclid=IwAR1NedqsVbFU6sttD7PHWY_LwIgwk77tNKbi3OaYLP3-PnhytI-J4or5nZY#slide=id.g25d18931cb7_3_0

**Comment by KazelVillamarzo** [comment]
Guidelines Link:
https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit?fbclid=IwAR1NedqsVbFU6sttD7PHWY_LwIgwk77tNKbi3OaYLP3-PnhytI-J4or5nZY#slide=id.g25d18931cb7_3_0

**Comment by mingoedjudah** [comment]
@nogadas-vonryan 

All files should be named snake case. Refer to slide 15 second bullet of the coding guidelines.

https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/nogadas_vonryan/nogadas_vonryan.html#L24

https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/nogadas_vonryan/nogadas_vonryan.html#L27

https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/nogadas_vonryan/nogadas_vonryan.html#L30

https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/nogadas_vonryan/nogadas_vonryan.html#L33

https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/nogadas_vonryan/nogadas_vonryan.html#L36

https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/nogadas_vonryan/nogadas_vonryan.html#L39

---
Coding Guidelines:
https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit?fbclid=IwAR38oipQEtK5lSu37SXTl3zwpEu9ap1GZPut5-F-LVDu6GtoJ1KpPIxhMCs#slide=id.g25d18931cb7_3_0

**Comment by alima-kailamarie** [comment]
All files should be named snake case. Refer to slide 15 second bullet of the coding guidelines.
- - -
https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit?fbclid=IwAR1lw-fYFJoyU3Zd8xuasXE5Pi9M6HBHNvyXQhX_UigWsIFh_HM5tA-jJBw_aem_AZw6dkk88Ijvd-vTmoWhtyHTRRxWo93wb9ZLBom35XLUH8Yj_gBMV4naXQt39pb5oz2vkfvSXebSNNTl0ZO6fXbx#slide=id.g25d18931cb7_3_0

https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/roche_mauijane/work1.html

https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/roche_mauijane/work2.html

https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/roche_mauijane/work3.html

https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/roche_mauijane/work4.html

https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/roche_mauijane/work5.html

@roche-mauijane

**Comment by alima-kailamarie** [comment]
All files should be named snake case. Refer to slide 15 second bullet of the coding guidelines.
- - - 
https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit?fbclid=IwAR1lw-fYFJoyU3Zd8xuasXE5Pi9M6HBHNvyXQhX_UigWsIFh_HM5tA-jJBw_aem_AZw6dkk88Ijvd-vTmoWhtyHTRRxWo93wb9ZLBom35XLUH8Yj_gBMV4naXQt39pb5oz2vkfvSXebSNNTl0ZO6fXbx#slide=id.g25d18931cb7_3_0

https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/anonuevo_jheferson/Empty1.html

https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/anonuevo_jheferson/Empty2.html

https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/anonuevo_jheferson/Empty3.html

https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/anonuevo_jheferson/Empty4.html

https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/anonuevo_jheferson/Empty5.html

@anonuevo-jheferson

**Comment by nogadas-vonryan** [comment]
> @nogadas-vonryan
> 
> All files should be named snake case. Refer to slide 15 second bullet of the coding guidelines.
> 
> https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/nogadas_vonryan/nogadas_vonryan.html#L24
> 
> https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/nogadas_vonryan/nogadas_vonryan.html#L27
> 
> https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/nogadas_vonryan/nogadas_vonryan.html#L30
> 
> https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/nogadas_vonryan/nogadas_vonryan.html#L33
> 
> https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/nogadas_vonryan/nogadas_vonryan.html#L36
> 
> https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/nogadas_vonryan/nogadas_vonryan.html#L39
> 
> Coding Guidelines: https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit?fbclid=IwAR38oipQEtK5lSu37SXTl3zwpEu9ap1GZPut5-F-LVDu6GtoJ1KpPIxhMCs#slide=id.g25d18931cb7_3_0

Issue resolved. Fix on 16d44b9. Thank you.

**Comment by Cahigan-MarkLouie** [comment]
> @cahigan-marklouie All files should be named snake case. Refer to slide 15 second bullet of the coding guidelines. https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit?fbclid=IwAR1lw-fYFJoyU3Zd8xuasXE5Pi9M6HBHNvyXQhX_UigWsIFh_HM5tA-jJBw_aem_AZw6dkk88Ijvd-vTmoWhtyHTRRxWo93wb9ZLBom35XLUH8Yj_gBMV4naXQt39pb5oz2vkfvSXebSNNTl0ZO6fXbx#slide=id.g25d18931cb7_3_0
> 
> https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/cahigan_marklouie/cahigan_marklouie.html#L31
> 
> 
> https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/cahigan_marklouie/cahigan_marklouie.html#L34
> 
> 
> https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/cahigan_marklouie/cahigan_marklouie.html#L37
> 
> 
> https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/cahigan_marklouie/cahigan_marklouie.html#L40
> 
> 
> https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/cahigan_marklouie/cahigan_marklouie.html#L43
> 
> 
> https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/cahigan_marklouie/cahigan_marklouie.html#L5

Fix on 1886b4d2f4453c284d550fb8dfb69e01b71ce0da . Thank you.

**Comment by Anonuevo-Jheferson** [comment]
> All files should be named snake case. Refer to slide 15 second bullet of the coding guidelines.
> 
> https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit?fbclid=IwAR1lw-fYFJoyU3Zd8xuasXE5Pi9M6HBHNvyXQhX_UigWsIFh_HM5tA-jJBw_aem_AZw6dkk88Ijvd-vTmoWhtyHTRRxWo93wb9ZLBom35XLUH8Yj_gBMV4naXQt39pb5oz2vkfvSXebSNNTl0ZO6fXbx#slide=id.g25d18931cb7_3_0
> 
> https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/anonuevo_jheferson/Empty1.html
> 
> https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/anonuevo_jheferson/Empty2.html
> 
> https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/anonuevo_jheferson/Empty3.html
> 
> https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/anonuevo_jheferson/Empty4.html
> 
> https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/anonuevo_jheferson/Empty5.html
> 
> @anonuevo-jheferson

Resolved the issue, fix on 6bb4a68b44852d166a53177f7b25fa33840cc8f9. Thank you

**Comment by Roche-MauiJane** [comment]
> All files should be named snake case. Refer to slide 15 second bullet of the coding guidelines.
> 
> https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit?fbclid=IwAR1lw-fYFJoyU3Zd8xuasXE5Pi9M6HBHNvyXQhX_UigWsIFh_HM5tA-jJBw_aem_AZw6dkk88Ijvd-vTmoWhtyHTRRxWo93wb9ZLBom35XLUH8Yj_gBMV4naXQt39pb5oz2vkfvSXebSNNTl0ZO6fXbx#slide=id.g25d18931cb7_3_0
> 
> https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/roche_mauijane/work1.html
> 
> https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/roche_mauijane/work2.html
> 
> https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/roche_mauijane/work3.html
> 
> https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/roche_mauijane/work4.html
> 
> https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/roche_mauijane/work5.html
> 
> @roche-mauijane

Resolved the issue, Fix on 364620257dc9045abca17e784cabcc69e0eac334. Thankyou
