### ISSUE TITLE
Roche's Files Issues

### ISSUE THREAD

**Issue by fidel-dianarose** [PUP-BSIT/ex7-tuf_developers#6]
There should be a max of 80 col per line. Refer to slide 6 of the coding guidelines.

https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/roche_mauijane/mauijane.css#L2

https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/roche_mauijane/mauijane.css#L12

https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/roche_mauijane/mauijane.css#L33

https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/roche_mauijane/mauijane.css#L46

Remove unnecessary/excessive lines and spacing. Refer to slide 15 first bullet of the coding guidelines.

https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/roche_mauijane/roche_mauijane.html#L58

All files should be named in snake case, all lower case. Refer to the coding guidelines below:

https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/roche_mauijane/roche_mauijane.html#L28

https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/roche_mauijane/roche_mauijane.html#L29

https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/roche_mauijane/roche_mauijane.html#L30

https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/roche_mauijane/roche_mauijane.html#L31

https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/roche_mauijane/roche_mauijane.html#L32

Class names should be written in kebab case. Refer to slide 7 second bullet of the coding guidelines.

https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/roche_mauijane/roche_mauijane.html#L14

**Comment by mingoedjudah** [comment]
This is a duplicated issue.

**Comment by alima-kailamarie** [comment]
This is duplicate issue.
