### ISSUE TITLE
Unnecessary lines/spacing

### ISSUE THREAD

**Issue by mingoedjudah** [PUP-BSIT/ex7-tuf_developers#7]
@nogadas-vonryan 

Remove unnecessary/excessive lines and spacing on your html file line 61 and 62. Refer to slide 15 first bullet of the coding guidelines.

---
Coding Guidelines:
https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit?fbclid=IwAR38oipQEtK5lSu37SXTl3zwpEu9ap1GZPut5-F-LVDu6GtoJ1KpPIxhMCs#slide=id.g25d18931cb7_3_0

**Comment by Villamarzo-Kazel** [comment]
@cahigan-marklouie 
Remove unnecessary/excessive lines and spacing on your html line 9. Refer to slide 15 first bullet of the coding guidelines.
Coding Guidelines:
https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit?fbclid=IwAR38oipQEtK5lSu37SXTl3zwpEu9ap1GZPut5-F-LVDu6GtoJ1KpPIxhMCs#slide=id.g25d18931cb7_3_0
https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/cahigan_marklouie/work2.html#L9

**Comment by alima-kailamarie** [comment]
Remove unnecessary/excessive lines and spacing on your html file line 61 and 62. Refer to slide 15 first bullet of the coding guidelines below:
- - -
https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit?fbclid=IwAR38oipQEtK5lSu37SXTl3zwpEu9ap1GZPut5-F-LVDu6GtoJ1KpPIxhMCs#slide=id.g25d18931cb7_3_0

https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/roche_mauijane/roche_mauijane.html#L58

@roche-mauijane

**Comment by nogadas-vonryan** [comment]
> @nogadas-vonryan
> 
> Remove unnecessary/excessive lines and spacing on your html file line 61 and 62. Refer to slide 15 first bullet of the coding guidelines.
> 
> Coding Guidelines: https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit?fbclid=IwAR38oipQEtK5lSu37SXTl3zwpEu9ap1GZPut5-F-LVDu6GtoJ1KpPIxhMCs#slide=id.g25d18931cb7_3_0

Issue resolved. Fix on 0ef0b29. Thank you.

**Comment by Cahigan-MarkLouie** [comment]
> @cahigan-marklouie Remove unnecessary/excessive lines and spacing on your html line 9. Refer to slide 15 first bullet of the coding guidelines. Coding Guidelines: https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit?fbclid=IwAR38oipQEtK5lSu37SXTl3zwpEu9ap1GZPut5-F-LVDu6GtoJ1KpPIxhMCs#slide=id.g25d18931cb7_3_0
> 
> https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/cahigan_marklouie/work2.html#L9

Fix on 52e1ed8a6d81d20635ae3d662e8515f199ee7a79 . Thank you.

**Comment by Roche-MauiJane** [comment]
> Remove unnecessary/excessive lines and spacing on your html file line 61 and 62. Refer to slide 15 first bullet of the coding guidelines below:
> 
> https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit?fbclid=IwAR38oipQEtK5lSu37SXTl3zwpEu9ap1GZPut5-F-LVDu6GtoJ1KpPIxhMCs#slide=id.g25d18931cb7_3_0
> 
> https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/roche_mauijane/roche_mauijane.html#L58
> 
> @roche-mauijane

Resolved the issue, Fix on 364620257dc9045abca17e784cabcc69e0eac334. Thank you.
