### ISSUE TITLE
Add new line/spacing

### ISSUE THREAD

**Issue by mingoedjudah** [PUP-BSIT/ex7-tuf_developers#8]
@nogadas-vonryan 

Add a new line or break the line after closing the element for readability.  Refer to slide 15 first bullet of the coding guidelines.

https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/nogadas_vonryan/nogadas_vonryan.html#L9

https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/nogadas_vonryan/nogadas_vonryan.html#L19

https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/nogadas_vonryan/nogadas_vonryan.html#L42

https://github.com/PUP-BSIT/ex7-tuf_developers/blob/19f88c7bed3a69d570c9bb0e96ab286bb73b7627/nogadas_vonryan/nogadas_vonryan.html#L49

---
Coding Guidelines:
https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit?fbclid=IwAR38oipQEtK5lSu37SXTl3zwpEu9ap1GZPut5-F-LVDu6GtoJ1KpPIxhMCs#slide=id.g25d18931cb7_3_0

**Comment by nogadas-vonryan** [comment]
Issue resolved. Fix on 0ef0b29. Thank you.
